### PR TITLE
Release GliaSDK 0.30.0

### PR DESCRIPTION
**Pull request by dukhovnyi**

### CODE REVIEW

**Review by gersonnoboa — APPROVED** [review]

**Review by gugalo — COMMENTED** [review]
Should the `package.json` have version updated?
https://github.com/salemove/ios-bundle/blob/1f2756a6e30b5731d398e192265fbebba9b1b91d/package.json#L3

**Review by igorkravchenko — APPROVED** [review]
Since it is only checksum changes, I have nothing to add. Approved.

**Review by gugalo — APPROVED** [review]

**Comment by dukhovnyi** [comment]
> Should the `package.json` have version updated?
> https://github.com/salemove/ios-bundle/blob/1f2756a6e30b5731d398e192265fbebba9b1b91d/package.json#L3

package.json is the configuration file for a ReactNative project, since officially we don't support ReactNative I didn't change it.

**Comment by dukhovnyi** [comment]
!merge

**Pull request merged**
